vim.keymap.set("n", "<leader>gf", vim.cmd.Git, {desc="Open Git panel (of Git Fugitive)"})
vim.keymap.set("n", '<leader>gp', function() vim.cmd[[Git push]] end, { desc="Push commits" })
vim.keymap.set("n",'<leader>gc', function() 
	local message = vim.fn.input("Message > ")
	vim.cmd('Git commit -m "' .. message..'"')
end, { desc="Record changes to the repository" })
vim.keymap.set("n", '<leader>ga', function()
	local path = vim.fn.expand('%p')
	vim.cmd("Git add "..path)
end, {desc="Add current changes to the working directory"})
vim.keymap.set("n", '<leader>gA', function() 
	vim.cmd[[Git add .]]
end, {desc="Add all changes to the working directory"})
vim.keymap.set("n", '<leader>gu', function()
	local path = vim.fn.expand('%p')
	vim.cmd("Git restore --staged ".. path)
end, { desc="Unstage current changes from the working directory" })
